site_name: SPIN ONE
nav:
  - Home: readme.md
  - Contentful: Contentful/readme.md
  - Gatsby: Gatsby/readme.md
  - DNS: DNS/readme.md
  - netlify: netlify/readme.md
  - Google: Google/readme.md
theme: readthedocs
